gpu_id: 0
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'expMSVD-QA'
model_type: 'DualVGR'
graph_module: 'GAT'
graph_layers: 4

train:
  lr: 0.0001
  batch_size: 256
  restore: False
  max_epochs: 25
  word_dim: 300
  module_dim: 768
  glove: True
  num_of_nodes: 8 

val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'msvd-qa'
  data_dir: '/root/autodl-tmp/feature-data/msvd-qa'
  save_dir: '/root/autodl-tmp/results/'
